name: dart_api
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  shelf: ^1.3.0
  shelf_router: ^1.0.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
